const renders = "/mustuse%20image";
const references = "/reference_image";

export const IMAGES = {
  wafeePortrait: `${renders}/wafee.png`,
  wafeeAngle: `${renders}/wafee_angle_look.png`,
  wafeeCinematic: `${renders}/wafee_cenimatic.png`,
  wafeeStudio: `${renders}/ChatGPT%20Image%20Aug%201,%202026,%2004_58_40%20PM.png`,
  education: `${renders}/education.png`,
  doctor: `${renders}/doctor.png`,
  sample: `${references}/wafee%20sample.jpeg`,
  breakdown: `${references}/wafee%20breakdown.jpeg`,
  dimensions: `${references}/dimension%20and%20views.jpeg`,
  concept: `${references}/concept%20daigram.jpeg`,
  serviceArea: `${references}/service%20area.png`,
  fire: `${references}/wafee%20fire%20poster.png`,
  water: `${references}/water_poster%20.png`,
  underwater: `${references}/water_under_water.png`,
  airFlying: `${references}/wafee_air_flying.png`,
  airPhoto: `${references}/wafee_air%20photo.png`,
  space: `${references}/space_poster.png`,
  spaceTwo: `${references}/space_poster%20.png`,
  proto: `${references}/development_wafee_proto.png`,
  humanFriendly: `${references}/human%20friendly%20wafee%20poster.png`,
  qwafee: `${references}/qwafee%20poster.png`,
  seeThrough: `${references}/see%20through%20wafee%20design.png`,
  welcomeScene: `${renders}/cennzo_robo_welcome.png`,
  miningScene: `${renders}/wafee%20working%20in%20mining.png`,
  energyScene: `${renders}/wafee%20working%20in%20energy.png`,
  armyScene: `${renders}/wafee%20government%20army.png`,
  constructionScene: `${renders}/construction%20working.png`,
  logisticsScene: `${renders}/logistic_working.png`,
  manufacturingScene: `${renders}/manufacturing.jpeg`,
  oilGasScene: `${renders}/working%20in%20oil%20and%20gas.jpeg`,
  workingModel: `${renders}/working%20_model%20of%20wafee.jpeg`,
  homecareScene: `${renders}/homecare-humanoid.png`,
  mountainScene: `${renders}/humanoid%20seeing%20from%20mountain.png`,
} as const;